### ISSUE TITLE
run on Arduino board?

### ISSUE THREAD

**Issue by bbartling** [chipkin/BACnetServerExampleCPP#30]
I apologize if this is a silly question...but could run this run on an Arduino board on Wi-Fi? 

In research (smart building area) I am experimenting with Arduino boards and people counting technology and am curious if I can create a BACnet API of consisting of one or 2 BACnet discoverable integers points?

Basically am curious if I can discover the Arduino board via BACnet and pull in 1 or 2 points analogInput points to a building automation/IoT platform.

Thanks for any tips getting started am a bit new to C++ but am familiar with BACnet with prior work experiences as a field technician for automation.

**Comment by funvill** [comment]
Yes, this could work on an Arduino board with Wi-Fi. 
See this project that uses the Arduino SDK on a ESP32 https://github.com/chipkin/ESP32-BACnetServerExample. 

The CAS BACnet Stack is network agnostic so you will need to write your platform dependent SendMessage, RecvMessage for it work, shouldn't be too hard. 

Note: The CAS BACnet Stack is a paid for software library, Contact Chipkin.com for more information.
