### ISSUE TITLE
Cannot open include file CASBACnetStackAdapter.h

### ISSUE THREAD

**Issue by mochiman** [chipkin/BACnetServerExampleCPP#8]
I am recieving this error when I try to compile the BACnet server example when I try to compile this example in Visual Studio 2019.

`Cannot open include file: 'CASBACnetStackAdapter.h': No such file or directory	BACnetServerExample	BACnetServerExampleCPP\BACnetServerExample\BACnetServerExample.cpp`

Where is this file and how do I compile this example?

**Comment by ssmethurst** [comment]
The `CASBACnetStackAdapter.h` is located in the CAS BACnet Stack submodule `\BACnetServerExampleCPP\submodules\cas-bacnet-stack\adapters\cpp` 

You will need to checkout the `cas-bacnet-stack` sub module as well. 

More information about the CAS BACnet Stack can be found here https://store.chipkin.com/services/stacks/bacnet-stack
